import { router, json, error, requireAuth, db, secrets, ai, storage } from '@appdeploy/sdk';

type Body = Record<string, unknown>;
type GeoPoint = { lat: number; lon: number; name: string };
type NearbyPlace = { name: string; lat: number; lon: number; kind: 'rail' | 'bus' | 'airport'; code?: string; address?: string };
async function photonTransportSearch(point: GeoPoint, kind: NearbyPlace['kind'], queryTerm: string): Promise<NearbyPlace[]> {
  try {
    const response = await fetch(`https://photon.komoot.io/api/?q=${encodeURIComponent(`${point.name} ${queryTerm}, India`)}&limit=8&lang=en`, { headers: { 'User-Agent': 'GoldenPerfectTravel/1.0' } });
    if (!response.ok) return [];
    const data = await response.json() as { features?: Array<{ geometry?: { coordinates?: number[] }; properties?: { name?: string; city?: string; state?: string; postcode?: string } }> };
    return (data.features || []).map((feature) => {
      const coordinates = feature.geometry?.coordinates;
      const props = feature.properties || {};
      return { name: props.name || queryTerm, lat: Number(coordinates?.[1]), lon: Number(coordinates?.[0]), kind, address: [props.city, props.state, props.postcode].filter(Boolean).join(', ') };
    }).filter((item) => Number.isFinite(item.lat) && Number.isFinite(item.lon))
      .sort((a, b) => distanceScore(point.lat, point.lon, a.lat, a.lon) - distanceScore(point.lat, point.lon, b.lat, b.lon))
      .filter((item, index, all) => all.findIndex((candidate) => `${candidate.kind}:${candidate.name}` === `${item.kind}:${item.name}`) === index)
      .slice(0, 8);
  } catch { return []; }
}
const TRAIN_SNAPSHOT_URL = 'https://raw.githubusercontent.com/datameet/railways/master/trains.json';
let trainSnapshotPromise: Promise<unknown[]> | null = null;
function distanceScore(aLat: number, aLon: number, bLat: number, bLon: number) { const lat = (aLat - bLat) * 111; const lon = (aLon - bLon) * 111 * Math.cos((aLat * Math.PI) / 180); return Math.sqrt(lat * lat + lon * lon); }
async function geocodePhoton(query: string): Promise<GeoPoint | null> { try { const response = await fetch(`https://photon.komoot.io/api/?q=${encodeURIComponent(`${query}, India`)}&limit=1&lang=en`, { headers: { 'User-Agent': 'GoldenPerfectTravel/1.0' } }); if (!response.ok) return null; const data = await response.json() as { features?: Array<{ geometry?: { coordinates?: number[] }; properties?: { name?: string; city?: string; state?: string } }> }; const feature = data.features?.[0]; const coordinates = feature?.geometry?.coordinates; if (!coordinates || coordinates.length < 2) return null; return { lat: Number(coordinates[1]), lon: Number(coordinates[0]), name: [feature.properties?.name, feature.properties?.city, feature.properties?.state].filter(Boolean).join(', ') || query }; } catch { return null; } }
async function nearbyTransport(point: GeoPoint): Promise<NearbyPlace[]> { const query = `[out:json][timeout:20];(nwr[railway~"station|halt"](around:18000,${point.lat},${point.lon});nwr[amenity="bus_station"](around:18000,${point.lat},${point.lon});nwr[public_transport="station"][bus=yes](around:18000,${point.lat},${point.lon});nwr[aeroway="aerodrome"](around:40000,${point.lat},${point.lon}););out center tags;`; try { const response = await fetch('https://overpass-api.de/api/interpreter', { method: 'POST', headers: { 'Content-Type': 'text/plain', 'User-Agent': 'GoldenPerfectTravel/1.0' }, body: query }); if (!response.ok) return []; const data = await response.json() as { elements?: Array<{ lat?: number; lon?: number; center?: { lat: number; lon: number }; tags?: Record<string, string> }> }; return (data.elements || []).map((item) => { const lat = Number(item.lat ?? item.center?.lat); const lon = Number(item.lon ?? item.center?.lon); const tags = item.tags || {}; const kind: NearbyPlace['kind'] = tags.aeroway === 'aerodrome' ? 'airport' : tags.railway ? 'rail' : 'bus'; return { name: tags.name || tags['name:en'] || (kind === 'rail' ? 'Railway station' : kind === 'bus' ? 'Bus station' : 'Airport'), lat, lon, kind, code: tags['railway:ref'] || tags.ref || tags.iata, address: tags['addr:city'] || tags['addr:street'] }; }).filter((item) => Number.isFinite(item.lat) && Number.isFinite(item.lon)).sort((a, b) => distanceScore(point.lat, point.lon, a.lat, a.lon) - distanceScore(point.lat, point.lon, b.lat, b.lon)).filter((item, index, all) => all.findIndex((candidate) => `${candidate.kind}:${candidate.name}` === `${item.kind}:${item.name}`) === index).slice(0, 10); } catch { return []; } }
async function loadTrainSnapshot() { if (!trainSnapshotPromise) trainSnapshotPromise = fetch(TRAIN_SNAPSHOT_URL, { headers: { 'User-Agent': 'GoldenPerfectTravel/1.0' } }).then(async (response) => response.ok ? await response.json() as unknown[] : []).catch(() => []); return trainSnapshotPromise; }
async function findTrainReferences(origin: GeoPoint, destination: GeoPoint) { const raw = await loadTrainSnapshot(); return raw.flatMap((item) => { const feature = item as { geometry?: { coordinates?: number[][] }; properties?: Record<string, unknown> }; const coordinates = feature.geometry?.coordinates; const properties = feature.properties; if (!coordinates?.length || !properties) return []; const first = coordinates[0]; const last = coordinates[coordinates.length - 1]; if (!first || !last || first.length < 2 || last.length < 2) return []; const direct = distanceScore(origin.lat, origin.lon, Number(first[1]), Number(first[0])) + distanceScore(destination.lat, destination.lon, Number(last[1]), Number(last[0])); const reverse = distanceScore(origin.lat, origin.lon, Number(last[1]), Number(last[0])) + distanceScore(destination.lat, destination.lon, Number(first[1]), Number(first[0])); if (Math.min(direct, reverse) > 180) return []; return [{ number: String(properties.number || ''), name: String(properties.name || ''), type: String(properties.type || 'Train'), from: String(properties.from_station_name || ''), to: String(properties.to_station_name || ''), score: Math.min(direct, reverse) }]; }).filter((item) => item.number && item.name).sort((a, b) => a.score - b.score).slice(0, 8); }
async function fetchPageText(url: string) { try { const response = await fetch(url, { headers: { 'User-Agent': 'GoldenPerfectTravel/1.0' } }); if (!response.ok) return ''; const html = await response.text(); return html.replace(/<script[\s\S]*?<\/script>/gi, ' ').replace(/<style[\s\S]*?<\/style>/gi, ' ').replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').slice(0, 24000); } catch { return ''; } }
async function buildAiRouteAnswer(from: string, to: string, date: string, context: unknown) { const fromSlug = encodeURIComponent(from.trim().toLowerCase().replace(/\\s+/g, '-')); const toSlug = encodeURIComponent(to.trim().toLowerCase().replace(/\\s+/g, '-')); const urls = [`https://www.ixigo.com/by-train-rail/${fromSlug}-to-${toSlug}-by-train`, `https://www.redbus.in/bus-tickets/${fromSlug}-to-${toSlug}`, `https://www.makemytrip.com/bus-tickets/${fromSlug}-${toSlug}_bus-ticket-booking.html`, `https://www.google.com/travel/flights?q=${encodeURIComponent(`Flights from ${from} to ${to}${date ? ` on ${date}` : ''}`)}`]; const pages = await Promise.all(urls.map(fetchPageText)); const sourceBundle = pages.map((text, index) => `SOURCE ${index + 1}: ${urls[index]}\\n${text}`).join('\\n\\n'); const result = await ai.run({ system: 'You are the live travel-planning engine for an India travel app. Give practical, route-specific answers. Use only facts supported by the supplied map/timetable/provider source text or clearly label an item as needing live verification. Never invent train numbers, bus operators, flight numbers, prices, timings, stations, airports, seats or availability. If direct service is not supported, explain a sensible connection using only supported locations/services; otherwise say that a connection must be checked live. Prefer exact names, numbers, prices, timings, boarding points and arrival points when present. Include a short map/search instruction using the supplied real locations. Mention that prices and availability can change by date.', prompt: `Plan ${from} to ${to}${date ? ` for ${date}` : ''}. Return a concise but useful answer with sections: BEST DIRECT OPTIONS, IF NO DIRECT SERVICE, TRAIN, BUS, FLIGHT, BOARDING/ARRIVAL LOCATIONS, PRICE & TIME, and VERIFICATION. Context: ${JSON.stringify(context)}\\nProvider source text: ${sourceBundle}`, maxSteps: 4, maxTokens: 1800, thinkingMode: 'FAST' }); return result.text; }
async function buildTravelRecommendation(body: Body) { const from = String(body.from || '').trim(); const to = String(body.to || '').trim(); const date = String(body.date || '').trim(); if (!from || !to) return null; const [origin, destination] = await Promise.all([geocodePhoton(from), geocodePhoton(to)]); if (!origin || !destination) return { found: false, message: 'Could not locate the origin or destination. Try a city name, railway station, airport or district.' }; const [originTransportRaw, destinationTransportRaw, trains] = await Promise.all([nearbyTransport(origin), nearbyTransport(destination), findTrainReferences(origin, destination)]);
  const originTransport = originTransportRaw.length ? originTransportRaw : (await Promise.all([photonTransportSearch(origin, 'rail', 'railway station'), photonTransportSearch(origin, 'bus', 'bus station'), photonTransportSearch(origin, 'airport', 'airport')])).flat();
  const destinationTransport = destinationTransportRaw.length ? destinationTransportRaw : (await Promise.all([photonTransportSearch(destination, 'rail', 'railway station'), photonTransportSearch(destination, 'bus', 'bus station'), photonTransportSearch(destination, 'airport', 'airport')])).flat(); const mapped = { origin: { rail: originTransport.filter((x) => x.kind === 'rail').slice(0, 5), bus: originTransport.filter((x) => x.kind === 'bus').slice(0, 5), airport: originTransport.filter((x) => x.kind === 'airport').slice(0, 4) }, destination: { rail: destinationTransport.filter((x) => x.kind === 'rail').slice(0, 5), bus: destinationTransport.filter((x) => x.kind === 'bus').slice(0, 5), airport: destinationTransport.filter((x) => x.kind === 'airport').slice(0, 4) } }; let aiAnswer = ''; try { aiAnswer = await buildAiRouteAnswer(from, to, date, { resolvedOrigin: origin, resolvedDestination: destination, trains, mapped }); } catch (err) { console.warn('AI route answer unavailable', err); } return { found: true, origin: { ...origin, railStations: mapped.origin.rail, busStops: mapped.origin.bus, airports: mapped.origin.airport }, destination: { ...destination, railStations: mapped.destination.rail, busStops: mapped.destination.bus, airports: mapped.destination.airport }, trains, trainData: trains.length ? 'reference_snapshot' : 'not_found', trainDataNote: 'Train names shown from a public timetable snapshot. Verify running day, platform, live status and fare on an official/current railway service before booking.', officialTrainSearchUrl: 'https://www.indianrail.gov.in/enquiry/SEAT/SeatAvailability.html?locale=en', aiAnswer, generatedAt: new Date().toISOString(), mapAttribution: 'Transport locations from OpenStreetMap contributors.' }; }

async function nextBookingNumber() {
  const result = await db.list<{ value?: number }>('booking_sequences', { limit: 1 });
  if (!result.items[0]) {
    const [id] = await db.add('booking_sequences', [{ value: 1 }]);
    if (!id) throw new Error('Could not initialize booking number sequence');
    return 1;
  }
  const current = result.items[0];
  const next = Math.max(1, Number(current.value || 0) + 1);
  const ok = await db.update('booking_sequences', [{ id: current.id, record: { value: next } }]);
  if (!ok[0]) throw new Error('Could not update booking number sequence');
  return next;
}

const ADMIN_USERNAME = 'abhaykumar456@#';
const ADMIN_SESSION_TTL_MS = 8 * 60 * 60 * 1000;

async function hasAdminSession(userId: string) {
  const result = await db.list<{ expiresAt?: string }>('admin_sessions', { limit: 20, filter: { userId } });
  const now = Date.now();
  return result.items.some((session) => Number(new Date(session.expiresAt || 0)) > now);
}

async function requireAdminSession(ctx: Parameters<ReturnType<typeof router>>[0]) {
  if (!ctx.user?.userId || !(await hasAdminSession(ctx.user.userId))) return error('Admin login required', 401);
  return null;
}

type NotesPlaceRecord = { userId: string; name: string; location: string; imagePath?: string; imageUrl?: string; favorite: boolean; createdAt: string; updatedAt: string };
type NotesRecord = { userId: string; placeId: string; day: number; date: string; time: string; title: string; text: string; location: string; tag: string; favorite: boolean; checklist: Array<{ text: string; done: boolean }>; expenseLabel: string; expenseAmount: number; photoPath?: string; photoUrl?: string; createdAt: string; updatedAt: string };

async function listUserPlaces(userId: string) { const items: Array<NotesPlaceRecord & { id: string }> = []; let nextToken: string | undefined; for (let page = 0; page < 10; page += 1) { const result = await db.list<NotesPlaceRecord>('travel_note_places', { limit: 50, nextToken, filter: { userId } }); items.push(...result.items); if (!result.nextToken) break; nextToken = result.nextToken; } return { items }; }
async function listUserNotes(userId: string) { const items: Array<NotesRecord & { id: string }> = []; let nextToken: string | undefined; for (let page = 0; page < 10; page += 1) { const result = await db.list<NotesRecord>('travel_notes', { limit: 100, nextToken, filter: { userId } }); items.push(...result.items); if (!result.nextToken) break; nextToken = result.nextToken; } return { items }; }
async function withSignedUrls<T extends { imagePath?: string; photoPath?: string }>(items: Array<T>) {
  const paths = items.flatMap((item) => [item.imagePath, item.photoPath]).filter((path): path is string => Boolean(path));
  if (!paths.length) return items;
  const unique = Array.from(new Set(paths));
  const urls = await storage.url(unique);
  const map = new Map(urls.map((item) => [item.path, item.url]));
  return items.map((item) => ({ ...item, imageUrl: item.imagePath ? map.get(item.imagePath) : undefined, photoUrl: item.photoPath ? map.get(item.photoPath) : undefined }));
}
async function deleteStoredPaths(paths: Array<string | undefined>) { const clean = paths.filter((path): path is string => Boolean(path)); if (clean.length) await storage.delete(Array.from(new Set(clean))); }

export const handler = router({
  'GET /api/travel-notes': [requireAuth(), async (ctx) => { const [placesResult, notesResult] = await Promise.all([listUserPlaces(ctx.user!.userId), listUserNotes(ctx.user!.userId)]); const places = await withSignedUrls(placesResult.items); const notes = await withSignedUrls(notesResult.items); return json({ places, notes }); }],
  'POST /api/travel-notes/places': [requireAuth(), async (ctx) => { const body = ctx.body as Body; const name = String(body.name || '').trim(); if (!name) return error('Place name is required', 400); const now = new Date().toISOString(); const existing = (await listUserPlaces(ctx.user!.userId)).items.find((item) => item.name.toLowerCase() === name.toLowerCase()); if (existing) return error('This place already exists', 409); const [id] = await db.add('travel_note_places', [{ userId: ctx.user!.userId, name, location: String(body.location || '').trim(), imagePath: String(body.imagePath || '').trim() || undefined, favorite: Boolean(body.favorite), createdAt: now, updatedAt: now }]); return id ? json({ id, created: true }, 201) : error('Could not create place', 500); }],
  'PUT /api/travel-notes/places/:id': [requireAuth(), async (ctx) => { const current = await db.get<NotesPlaceRecord>('travel_note_places', [ctx.params.id]); const existing = current[0]; if (!existing || existing.userId !== ctx.user!.userId) return error('Place not found', 404); const body = ctx.body as Body; const updated: NotesPlaceRecord = { ...existing, name: String(body.name ?? existing.name).trim(), location: String(body.location ?? existing.location).trim(), imagePath: String(body.imagePath ?? existing.imagePath ?? '').trim() || undefined, favorite: typeof body.favorite === 'boolean' ? body.favorite : existing.favorite, updatedAt: new Date().toISOString() }; const [ok] = await db.update('travel_note_places', [{ id: ctx.params.id, record: updated as unknown as Record<string, unknown> }]); if (!ok) return error('Could not update place', 500); if (existing.imagePath && existing.imagePath !== updated.imagePath) await deleteStoredPaths([existing.imagePath]); return json({ updated: true }); }],
  'DELETE /api/travel-notes/places/:id': [requireAuth(), async (ctx) => { const current = await db.get<NotesPlaceRecord>('travel_note_places', [ctx.params.id]); const existing = current[0]; if (!existing || existing.userId !== ctx.user!.userId) return error('Place not found', 404); const notes = (await listUserNotes(ctx.user!.userId)).items.filter((item) => item.placeId === ctx.params.id); const ids = notes.map((item) => item.id); if (ids.length) await db.delete('travel_notes', ids); await deleteStoredPaths([existing.imagePath, ...notes.map((item) => item.photoPath)]); const [ok] = await db.delete('travel_note_places', [ctx.params.id]); return ok ? json({ deleted: true }) : error('Could not delete place', 500); }],
  'POST /api/travel-notes': [requireAuth(), async (ctx) => { const body = ctx.body as Body; const placeId = String(body.placeId || '').trim(); const place = (await db.get<NotesPlaceRecord>('travel_note_places', [placeId]))[0]; if (!place || place.userId !== ctx.user!.userId) return error('Place not found', 404); const now = new Date().toISOString(); const [id] = await db.add('travel_notes', [{ userId: ctx.user!.userId, placeId, day: Math.max(1, Number(body.day || 1)), date: String(body.date || ''), time: String(body.time || ''), title: String(body.title || 'Travel Note'), text: String(body.text || ''), location: String(body.location || ''), tag: String(body.tag || '#travel'), favorite: Boolean(body.favorite), checklist: Array.isArray(body.checklist) ? body.checklist : [], expenseLabel: String(body.expenseLabel || ''), expenseAmount: Math.max(0, Number(body.expenseAmount || 0)), photoPath: String(body.photoPath || '').trim() || undefined, createdAt: now, updatedAt: now }]); return id ? json({ id, created: true }, 201) : error('Could not save travel note', 500); }],
  'PUT /api/travel-notes/:id': [requireAuth(), async (ctx) => { const current = await db.get<NotesRecord>('travel_notes', [ctx.params.id]); const existing = current[0]; if (!existing || existing.userId !== ctx.user!.userId) return error('Note not found', 404); const body = ctx.body as Body; const updated: NotesRecord = { ...existing, day: Math.max(1, Number(body.day ?? existing.day)), date: String(body.date ?? existing.date), time: String(body.time ?? existing.time), title: String(body.title ?? existing.title), text: String(body.text ?? existing.text), location: String(body.location ?? existing.location), tag: String(body.tag ?? existing.tag), favorite: typeof body.favorite === 'boolean' ? body.favorite : existing.favorite, checklist: Array.isArray(body.checklist) ? body.checklist : existing.checklist, expenseLabel: String(body.expenseLabel ?? existing.expenseLabel), expenseAmount: Math.max(0, Number(body.expenseAmount ?? existing.expenseAmount)), photoPath: String(body.photoPath ?? existing.photoPath ?? '').trim() || undefined, updatedAt: new Date().toISOString() }; const [ok] = await db.update('travel_notes', [{ id: ctx.params.id, record: updated as unknown as Record<string, unknown> }]); if (!ok) return error('Could not update travel note', 500); if (existing.photoPath && existing.photoPath !== updated.photoPath) await deleteStoredPaths([existing.photoPath]); return json({ updated: true }); }],
  'DELETE /api/travel-notes/:id': [requireAuth(), async (ctx) => { const current = await db.get<NotesRecord>('travel_notes', [ctx.params.id]); const existing = current[0]; if (!existing || existing.userId !== ctx.user!.userId) return error('Note not found', 404); await deleteStoredPaths([existing.photoPath]); const [ok] = await db.delete('travel_notes', [ctx.params.id]); return ok ? json({ deleted: true }) : error('Could not delete travel note', 500); }],
  'POST /api/travel-notes/upload': [requireAuth(), async (ctx) => { const body = ctx.body as Body; const data = String(body.data || ''); const contentType = String(body.contentType || 'image/jpeg'); const kind = String(body.kind || 'photo'); const sourceId = String(body.sourceId || '').replace(/[^a-zA-Z0-9_-]/g, ''); if (!data.startsWith('data:') && !/^[A-Za-z0-9+/=]+$/.test(data)) return error('Invalid image data', 400); const base64 = data.startsWith('data:') ? data.slice(data.indexOf(',') + 1) : data; if (!base64) return error('Image data is empty', 400); const path = `users/${ctx.user!.userId}/travel-notes/${kind}/${sourceId || crypto.randomUUID()}.jpg`; const [ok] = await storage.write([{ path, content: base64, contentType }]); if (!ok) return error('Could not store image', 500); const [{ url }] = await storage.url([path]); return json({ path, url }); }],
  'POST /api/travel-notes/migrate': [requireAuth(), async (ctx) => { const body = ctx.body as Body; const legacyPlaces = Array.isArray(body.places) ? body.places.slice(0, 100) : []; const legacyNotes = Array.isArray(body.notes) ? body.notes.slice(0, 300) : []; const existingPlaces = (await listUserPlaces(ctx.user!.userId)).items; const existingNotes = (await listUserNotes(ctx.user!.userId)).items; const placeByName = new Map(existingPlaces.map((item) => [item.name.toLowerCase(), item.id])); const createdPlaceIds = new Map<string, string>(); for (const item of legacyPlaces) { const name = String(item.name || '').trim(); if (!name) continue; const found = placeByName.get(name.toLowerCase()); if (found) { createdPlaceIds.set(String(item.id || name), found); continue; } const [id] = await db.add('travel_note_places', [{ userId: ctx.user!.userId, name, location: String(item.location || ''), favorite: Boolean(item.favorite), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }]); if (id) { placeByName.set(name.toLowerCase(), id); createdPlaceIds.set(String(item.id || name), id); } } const existingLegacyKeys = new Set(existingNotes.map((item) => `${item.title}|${item.date}|${item.text.slice(0, 80)}`)); const addable = legacyNotes.filter((item) => { const key = `${String(item.title || 'Travel Note')}|${String(item.date || '')}|${String(item.text || '').slice(0, 80)}`; return !existingLegacyKeys.has(key); }).map((item) => { const placeId = createdPlaceIds.get(String(item.placeId || item.place || '')) || placeByName.get(String(item.place || '').toLowerCase()); return placeId ? { userId: ctx.user!.userId, placeId, day: Math.max(1, Number(item.day || 1)), date: String(item.date || ''), time: String(item.time || ''), title: String(item.title || 'Travel Note'), text: String(item.text || ''), location: String(item.location || ''), tag: String(item.tag || '#travel'), favorite: Boolean(item.favorite), checklist: Array.isArray(item.checklist) ? item.checklist : [], expenseLabel: String(item.expenseLabel || ''), expenseAmount: Math.max(0, Number(item.expenseAmount || 0)), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() } : null; }).filter((item): item is Record<string, unknown> => Boolean(item)); if (addable.length) await db.add('travel_notes', addable); return json({ migratedPlaces: createdPlaceIds.size, migratedNotes: addable.length, keptLocalCopy: true }); }],
  'POST /api/travel-recommendation': [async (ctx) => { try { const result = await buildTravelRecommendation(ctx.body as Body); return result ? json(result) : error('Origin and destination are required', 400); } catch (err) { console.warn('Travel recommendation failed', err); return error('Travel recommendation is temporarily unavailable. Please try again.', 503); } }],
  'POST /api/ai-copilot': [async (ctx) => { const body = ctx.body as Body; const message = String(body.message || '').trim(); if (!message) return error('Message is required', 400); const context = String(body.context || '').slice(0, 8000); const conversation = Array.isArray(body.conversation) ? body.conversation.slice(-8).map((item) => String(item)).join('\\n') : ''; try { const result = await ai.run({ system: 'You are Golden Perfect AI, the practical copilot inside an India travel app. Understand Hindi, Hinglish and English. Be concise, friendly and action-oriented. Never invent live fares, availability, train numbers, flight numbers or booking confirmation. Use only destination names supplied in context when choosing a place. You are a controlled app agent. Allowed actions are none, open_plan, open_profile, search, travel_plan, open_place, save_place, delete_saved, delete_trip, request_cancel_booking. Never claim a mutation is completed; state-changing actions require explicit frontend confirmation. Use only IDs and place names supplied in context. Booking/payment submission and bank verification are never AI actions. For travel_plan, extract origin, destination, date and traveller count when the user supplied them; leave missing fields empty. For open_place use a known place name from context. Return the final response through emit_result.', prompt: `User request: ${message}\nApp context: ${context}`, tools: [{ name: 'emit_result', description: 'Return the final copilot response, app action and any trip fields explicitly understood from the request.', parameters: { type: 'object', properties: { reply: { type: 'string' }, action: { type: 'string', enum: ['none', 'open_plan', 'open_profile', 'search', 'travel_plan', 'open_place', 'save_place', 'delete_saved', 'delete_trip', 'request_cancel_booking'] }, query: { type: 'string' }, place: { type: 'string' }, from: { type: 'string' }, to: { type: 'string' }, date: { type: 'string' }, travelers: { type: 'number' } }, required: ['reply', 'action'] } }], maxSteps: 3, maxTokens: 900, thinkingMode: 'FAST', onToolCall: async () => ({ ok: true }) }); const data = (result.data || {}) as { reply?: string; action?: string; query?: string; place?: string; targetId?: string; from?: string; to?: string; date?: string; travelers?: number }; return json({ reply: data.reply || result.text || 'I can help you plan that.', action: data.action || 'none', query: data.query || '', place: data.place || '', targetId: data.targetId || '', from: data.from || '', to: data.to || '', date: data.date || '', travelers: Number.isFinite(data.travelers) ? data.travelers : 0 }); } catch { return error('AI assistant is temporarily unavailable. Please try again.', 503); } }],
  'GET /api/me': [requireAuth(), async (ctx) => json({ user: ctx.user })],
  'GET /api/saved': [requireAuth(), async (ctx) => { const result = await db.list('saved_places', { limit: 50, filter: { userId: ctx.user!.userId } }); return json(result.items); }],
  'POST /api/saved': [requireAuth(), async (ctx) => { const body = ctx.body as Body; const name = String(body.name || '').trim(); if (!name) return error('Place name is required', 400); const [id] = await db.add('saved_places', [{ userId: ctx.user!.userId, name }]); return id ? json({ id, name }, 201) : error('Could not save place', 500); }],
  'DELETE /api/saved/:name': [requireAuth(), async (ctx) => { const name = decodeURIComponent(ctx.params.name); const result = await db.list('saved_places', { limit: 50, filter: { userId: ctx.user!.userId, name } }); if (!result.items[0]) return json({ deleted: false }); const ok = await db.delete('saved_places', [result.items[0].id]); return json({ deleted: Boolean(ok[0]) }); }],
  'DELETE /api/trips/:id': [requireAuth(), async (ctx) => { const current = await db.get('trips', [ctx.params.id]); const existing = current[0] as (Record<string, unknown> & { userId?: string }) | null; if (!existing || existing.userId !== ctx.user!.userId) return error('Trip not found', 404); const ok = await db.delete('trips', [ctx.params.id]); return ok[0] ? json({ deleted: true }) : error('Could not delete trip', 500); }],
  'GET /api/trips': [requireAuth(), async (ctx) => { const result = await db.list('trips', { limit: 50, filter: { userId: ctx.user!.userId } }); return json(result.items); }],
  'POST /api/trips': [requireAuth(), async (ctx) => { const body = ctx.body as Body; const destination = String(body.to || '').trim(); if (!destination) return error('Destination is required', 400); const [id] = await db.add('trips', [{ userId: ctx.user!.userId, from: String(body.from || 'Delhi'), to: destination, date: String(body.date || ''), travelers: String(body.travelers || '1') }]); return id ? json({ id, saved: true }, 201) : error('Could not save trip', 500); }],
  'GET /api/bookings': [requireAuth(), async (ctx) => { const result = await db.list('bookings', { limit: 50, filter: { userId: ctx.user!.userId } }); return json(result.items); }],
  'POST /api/bookings/:id/cancel': [requireAuth(), async (ctx) => { const current = await db.get('bookings', [ctx.params.id]); const existing = current[0] as (Record<string, unknown> & { userId?: string; status?: string; paymentStatus?: string }) | null; if (!existing || existing.userId !== ctx.user!.userId) return error('Booking not found', 404); if (existing.status === 'cancelled' || existing.paymentStatus === 'cancelled') return json({ cancelled: true, alreadyCancelled: true }); const ok = await db.update('bookings', [{ id: ctx.params.id, record: { ...existing, status: 'cancelled', paymentStatus: 'cancelled', cancelledAt: new Date().toISOString() } }]); return ok[0] ? json({ cancelled: true, status: 'cancelled', paymentStatus: 'cancelled' }) : error('Could not cancel booking', 500); }],
  'POST /api/bookings': [requireAuth(), async (ctx) => { const body = ctx.body as Body; const place = String(body.place || '').trim(); const paymentReference = String(body.paymentReference || '').trim(); if (!place) return error('Place is required', 400); if (!paymentReference) return error('Payment reference is required after QR payment', 400); const travelers = Math.max(1, Math.min(20, Number(body.travelers || 1))); const distanceKm = Math.max(0, Number(body.distanceKm || 0)); const subtotal = Math.max(0, Number(body.subtotal || 0)); const gst = Math.max(0, Number(body.gst || 0)); const total = Math.max(0, Number(body.total || subtotal + gst)); const destination = String(body.destination || '').trim(); if (!destination) return error('Destination is required', 400); try { const bookingNumber = await nextBookingNumber(); const [id] = await db.add('bookings', [{ userId: ctx.user!.userId, customerName: String(ctx.user!.name || ''), customerEmail: String(ctx.user!.email || ''), bookingNumber, place, state: String(body.state || ''), from: String(body.from || 'Delhi'), destination, date: String(body.date || ''), travelers, distanceKm, subtotal, gst, total, paymentReference, status: 'confirmed_after_payment_reference', paymentStatus: 'payment_reference_submitted', adminDecision: 'pending', bookedAt: new Date().toISOString() }]); return id ? json({ id, bookingNumber, bookingStatus: 'confirmed_after_payment_reference', paymentStatus: 'payment_reference_submitted', total }, 201) : error('Could not save booking', 500); } catch { return error('Could not create a unique booking number', 500); } }],
  'GET /api/admin/me': [requireAuth(), async (ctx) => json({ isAdmin: Boolean(ctx.user?.userId && await hasAdminSession(ctx.user.userId)) })],
  'POST /api/admin/login': [requireAuth(), async (ctx) => { const body = ctx.body as Body; const username = String(body.username || '').trim(); const password = String(body.password || ''); if (username !== ADMIN_USERNAME) return error('Invalid admin credentials', 401); let configuredPassword = ''; try { configuredPassword = await secrets.readSecret('ADMIN_PASSWORD'); } catch { return error('Admin login is not configured', 503); } if (password !== configuredPassword) return error('Invalid admin credentials', 401); const expiresAt = new Date(Date.now() + ADMIN_SESSION_TTL_MS).toISOString(); const existing = await db.list('admin_sessions', { limit: 20, filter: { userId: ctx.user!.userId } }); if (existing.items.length) await db.delete('admin_sessions', existing.items.map((item) => item.id)); const [id] = await db.add('admin_sessions', [{ userId: ctx.user!.userId, expiresAt }]); return id ? json({ isAdmin: true, expiresAt }) : error('Could not create admin session', 500); }],
  'POST /api/admin/logout': [requireAuth(), async (ctx) => { const existing = await db.list('admin_sessions', { limit: 20, filter: { userId: ctx.user!.userId } }); if (existing.items.length) await db.delete('admin_sessions', existing.items.map((item) => item.id)); return json({ isAdmin: false }); }],
  'GET /api/admin/bookings': [requireAuth(), async (ctx) => { const denied = await requireAdminSession(ctx); if (denied) return denied; const result = await db.list('bookings', { limit: 200 }); return json(result.items); }],
  'PATCH /api/admin/bookings/:id': [requireAuth(), async (ctx) => { const denied = await requireAdminSession(ctx); if (denied) return denied; const decision = String((ctx.body as Body).adminDecision || '').trim(); if (!['approved', 'rejected', 'pending'].includes(decision)) return error('Invalid admin decision', 400); const current = await db.list('bookings', { limit: 1, filter: { id: ctx.params.id } }); const existing = current.items[0]; if (!existing) return error('Booking not found', 404); const ok = await db.update('bookings', [{ id: ctx.params.id, record: { ...existing, adminDecision: decision, adminReviewedAt: new Date().toISOString(), adminReviewedBy: ctx.user!.userId } }]); return ok[0] ? json({ updated: true, adminDecision: decision }) : error('Booking not found', 404); }],
});
