import { useMemo, useRef, useState } from 'react';

type Trip = { id: string; from: string; to: string; date: string; travelers: string };
type NoteType = 'text' | 'photo' | 'location' | 'checklist' | 'expense' | 'activity';
type NoteData = { src?: string; location?: { name: string; lat: number; lon: number }; items?: Array<{ text: string; checked: boolean }>; amount?: string; currency?: string; category?: string; activity?: string; expenseItems?: Array<{ description: string; amount: string; category: string }> };
type Note = { id: string; dateKey: string; createdAt: string; trip: string; groupName: string; title: string; text: string; type: NoteType; data?: NoteData };

const STORAGE = 'golden-perfect-rich-notes-v3';
const DAY_STORAGE = 'golden-perfect-rich-note-days';
const makeId = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
const todayKey = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
const moneySymbol = (currency?: string) => currency === 'EUR' ? '€' : currency === 'USD' ? '$' : currency === 'GBP' ? '£' : '₹';

export default function RichNotesPanel({ trips, notify }: { trips: Trip[]; notify: (message: string) => void }) {
  const [notes, setNotes] = useState<Note[]>(() => { try { const saved = JSON.parse(localStorage.getItem(STORAGE) || '[]') as Note[]; return saved.map((note) => ({ ...note, groupName: note.groupName || note.title || 'Travel Memory' })); } catch { return []; } });
  const tripOptions = useMemo(() => trips.length ? trips.map((trip) => ({ id: trip.id, label: `${trip.from || 'Unknown'} → ${trip.to || 'Unknown'}${trip.date ? ` · ${trip.date}` : ''}` })) : [{ id: 'quick', label: 'Quick trip · not saved in Trips' }], [trips]);
  const [trip, setTrip] = useState(() => localStorage.getItem('golden-perfect-note-trip') || '');
  const [text, setText] = useState('');
  const [groupName, setGroupName] = useState(() => localStorage.getItem('golden-perfect-note-group') || '');
  const [selectedGroup, setSelectedGroup] = useState('');
  const [detail, setDetail] = useState<Note | null>(null);
  const [action, setAction] = useState<NoteType | null>(null);
  const [title, setTitle] = useState('');
  const [checklist, setChecklist] = useState('');
  const [amount, setAmount] = useState('');
  const [expenseItems, setExpenseItems] = useState<Array<{ description: string; amount: string; category: string }>>([]);
  const [currency, setCurrency] = useState('INR');
  const [category, setCategory] = useState('Food');
  const [locationQuery, setLocationQuery] = useState('');
  const [activityDate, setActivityDate] = useState('');
  const [activityTime, setActivityTime] = useState('');
  const [activityDuration, setActivityDuration] = useState('');
  const [activityLocation, setActivityLocation] = useState('');
  const [locations, setLocations] = useState<Array<{ name: string; lat: number; lon: number; display: string }>>([]);
  const [pickedLocation, setPickedLocation] = useState<{ name: string; lat: number; lon: number } | null>(null);
  const photoRef = useRef<HTMLInputElement>(null);
  const groups = [...new Set(notes.map((note) => note.groupName || note.title || 'Travel Memory'))];
  const visibleGroup = selectedGroup;
  const groupNotes = notes.filter((note) => (note.groupName || note.title || 'Travel Memory') === visibleGroup);
  const persist = (next: Note[]) => { setNotes(next); localStorage.setItem(STORAGE, JSON.stringify(next)); };
  const create = (type: NoteType, noteTitle: string, noteText: string, data?: NoteData) => { const name = groupName.trim(); if (!name) { notify('Enter a place or memory name first.'); return; } const now = new Date(); const dateKey = todayKey(); const selectedTrip = trip || tripOptions[0]?.label || 'Current trip'; const entry: Note = { id: makeId(), dateKey, createdAt: now.toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }), trip: selectedTrip, groupName: name, title: noteTitle || 'Travel Note', text: noteText, type, data }; persist([entry, ...notes].slice(0, 150)); setSelectedGroup(''); setText(''); localStorage.setItem('golden-perfect-note-trip', selectedTrip); localStorage.setItem('golden-perfect-note-group', name); notify(`${entry.title} saved under ${name}`); };
  const saveText = () => { if (!text.trim()) { notify('Write something before saving.'); return; } create('text', text.trim().slice(0, 48), text.trim()); };
  const closeAction = () => { setAction(null); setTitle(''); setChecklist(''); setAmount(''); setExpenseItems([]); setCurrency('INR'); setCategory('Food'); setLocationQuery(''); setLocations([]); setPickedLocation(null); setActivityDate(''); setActivityTime(''); setActivityDuration(''); setActivityLocation(''); }; 
  const addExpenseItem = () => { const value = Number(amount); if (!Number.isFinite(value) || value <= 0) { notify('Enter a valid amount for this expense item.'); return; } setExpenseItems((items) => [...items, { description: title.trim() || `${category} expense`, amount: value.toFixed(2), category }]); setTitle(''); setAmount(''); };
  const removeExpenseItem = (index: number) => setExpenseItems((items) => items.filter((_, itemIndex) => itemIndex !== index));
  const expenseTotal = expenseItems.reduce((sum, item) => sum + Number(item.amount), 0);
  const saveChecklist = () => { const items = checklist.split('\n').map((item) => item.trim()).filter(Boolean).slice(0, 20); if (!items.length) { notify('Add at least one checklist item.'); return; } create('checklist', title.trim() || 'Travel Checklist', text.trim() || 'Checklist', { items: items.map((item) => ({ text: item, checked: false })) }); closeAction(); };
  const saveExpense = () => { const pending = Number(amount); const items = [...expenseItems]; if (Number.isFinite(pending) && pending > 0) items.push({ description: title.trim() || `${category} expense`, amount: pending.toFixed(2), category }); if (!items.length) { notify('Add at least one expense item.'); return; } const total = items.reduce((sum, item) => sum + Number(item.amount), 0); create('expense', 'Trip Expenses', text.trim() || `${items.length} expense item${items.length === 1 ? '' : 's'}`, { amount: total.toFixed(2), currency, category: 'Multiple', expenseItems: items }); closeAction(); };
  const findLocation = async () => { if (!locationQuery.trim()) { notify('Enter a place first.'); return; } try { const response = await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=in&q=${encodeURIComponent(locationQuery.trim() + ', India')}`); const rows = await response.json() as Array<{ name?: string; display_name?: string; lat: string; lon: string }>; setLocations(rows.map((row) => ({ name: row.name || row.display_name?.split(',')[0] || locationQuery, display: row.display_name || locationQuery, lat: Number(row.lat), lon: Number(row.lon) }))); } catch { notify('Location search is unavailable right now.'); } };
  const saveLocation = () => { if (!pickedLocation) { notify('Pick a location from the results.'); return; } create('location', title.trim() || pickedLocation.name, text.trim() || pickedLocation.name, { location: pickedLocation }); closeAction(); };
  const saveActivity = () => { const activityName = title.trim(); if (!activityName) { notify('Enter an activity name first.'); return; } if (!activityDate || !activityTime) { notify('Add the activity date and time.'); return; } if (!activityLocation.trim()) { notify('Add the activity location.'); return; } const details = [activityLocation.trim(), activityDate, activityTime, activityDuration.trim() ? `${activityDuration.trim()} min` : 'Duration not specified', text.trim() || 'No extra notes']; create('activity', activityName, details.join(' · '), { activity: activityName, activityDate, activityTime, activityDuration, activityLocation: activityLocation.trim(), activityNotes: text.trim() }); }; 
  const toggleItem = (id: string, index: number) => { const next = notes.map((note) => note.id === id && note.data?.items ? { ...note, data: { ...note.data, items: note.data.items.map((item, itemIndex) => itemIndex === index ? { ...item, checked: !item.checked } : item) } } : note); persist(next); if (detail?.id === id) setDetail(next.find((note) => note.id === id) || null); };
  const renameGroup = (currentName: string) => { const value = window.prompt('Rename this place / memory:', currentName); if (!value?.trim() || value.trim() === currentName) return; const nextName = value.trim().slice(0, 60); const next = notes.map((note) => (note.groupName || note.title || 'Travel Memory') === currentName ? { ...note, groupName: nextName } : note); persist(next); setSelectedGroup(nextName); if (groupName === currentName) { setGroupName(nextName); localStorage.setItem('golden-perfect-note-group', nextName); } notify('Section renamed'); };
  const updateNote = (note: Note) => { const nextTitle = window.prompt('Update title:', note.title); if (nextTitle === null) return; const cleanTitle = nextTitle.trim(); if (!cleanTitle) { notify('Title cannot be empty.'); return; } let nextText = note.text; let nextData = note.data; if (note.type === 'text' || note.type === 'activity') { const value = window.prompt('Update content:', note.text); if (value === null) return; if (!value.trim()) { notify('Content cannot be empty.'); return; } nextText = value.trim(); nextData = note.type === 'activity' ? { ...note.data, activity: value.trim() } : note.data; } else if (note.type === 'checklist') { const currentItems = note.data?.items || []; const value = window.prompt('Update checklist items, one per line:', currentItems.map((item) => item.text).join('\n')); if (value === null) return; const items = value.split('\n').map((item) => item.trim()).filter(Boolean).slice(0, 20); if (!items.length) { notify('Checklist cannot be empty.'); return; } nextData = { ...note.data, items: items.map((item, index) => ({ text: item, checked: currentItems[index]?.checked || false })) }; } else if (note.type === 'expense') { const value = window.prompt('Update expense amount:', note.data?.amount || ''); if (value === null) return; const numeric = Number(value); if (!Number.isFinite(numeric) || numeric <= 0) { notify('Enter a valid expense amount.'); return; } nextData = { ...note.data, amount: numeric.toFixed(2) }; } else if (note.type === 'location' && note.data?.location) { const value = window.prompt('Update location label:', note.data.location.name); if (value === null) return; if (!value.trim()) { notify('Location label cannot be empty.'); return; } nextData = { ...note.data, location: { ...note.data.location, name: value.trim() } }; nextText = value.trim(); } const next = notes.map((item) => item.id === note.id ? { ...item, title: cleanTitle.slice(0, 60), text: nextText, data: nextData } : item); persist(next); setDetail(next.find((item) => item.id === note.id) || null); notify('Content updated'); };
  const deleteNote = (id: string) => { if (!window.confirm('Delete this saved content?')) return; if (!window.confirm('Confirm again: permanently delete this content?')) return; persist(notes.filter((note) => note.id !== id)); setDetail(null); notify('Content deleted'); };
  const clearNotesHistory = () => { if (!notes.length) { notify('Notes history is already empty.'); return; } if (!window.confirm('Clear your entire My Travel Notes history?')) return; if (!window.confirm('Final confirmation: permanently delete ALL saved notes, photos, locations, checklists, expenses and activities?')) return; persist([]); setSelectedGroup(''); setDetail(null); notify('All notes history cleared'); };
  const handlePhoto = (file?: File) => { if (!file) return; if (file.size > 6 * 1024 * 1024) { notify('Choose a photo under 6 MB.'); return; } const reader = new FileReader(); reader.onload = () => create('photo', file.name.replace(/\.[^/.]+$/, '') || 'Travel Photo', text.trim() || 'Photo saved to this day.', { src: String(reader.result || '') }); reader.readAsDataURL(file); };
  const groupLabel = (name: string) => name || 'Travel Memory';
  const noteDescription = (note: Note) => { const value = note.text?.trim(); if (!value) return ''; if (note.type === 'location' && value === note.data?.location?.name) return ''; if (note.type === 'activity' && value === note.data?.activity) return ''; if (['Checklist', 'Expense logged', 'Photo saved to this day.'].includes(value)) return ''; return value; };
  return <section className='rich-notes-reference' data-reference='resources/design-reference-notes.png'>
    <header className='rich-notes-header'><div><span>06 · PRIVATE NOTES</span><h2>My Travel Notes</h2><p>Quickly capture memories and details. Add rich media or smart travel notes below.</p></div><b>SMART INPUT</b></header>
    <div className='rich-trip-date-row'><label>📍 Place / Memory Name<input value={groupName} onChange={(event) => setGroupName(event.target.value)} placeholder='e.g. Paris Trip, Varanasi, Hotel Stay' /></label><label>🧳 Trip<select value={trip} onChange={(event) => { setTrip(event.target.value); localStorage.setItem('golden-perfect-note-trip', event.target.value); }}><option value=''>Current trip</option>{tripOptions.map((item) => <option key={item.id} value={item.label}>{item.label}</option>)}</select></label><span>🗓️ {new Date().toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</span></div>
    <div className='rich-input-shell'><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder='Enter details (tap icons below for rich notes)…' /><div className='rich-quick-actions'><button onClick={() => photoRef.current?.click()}><span>📷</span><strong>Add Photo</strong></button><button onClick={() => { setAction('location'); setTitle('Tagged Location'); }}><span>📍</span><strong>Tag Location</strong></button><button onClick={() => { setAction('checklist'); setTitle('Travel Checklist'); }}><span>☑️</span><strong>Start Checklist</strong></button><button onClick={() => { setAction('expense'); setTitle('Travel Expense'); }}><span>💵</span><strong>Log Expense</strong></button><button onClick={() => { setAction('activity'); setTitle('Linked Activity'); }}><span>🔗</span><strong>Link Activity</strong></button></div><input ref={photoRef} className='rich-photo-input' type='file' accept='image/*' capture='environment' onChange={(event) => { handlePhoto(event.target.files?.[0]); event.currentTarget.value = ''; }} /><button className='primary-button full-button rich-save-button' onClick={saveText}>Save Rich Note</button></div>
    <div className='rich-daily-heading'><div><span>SAVED PLACES & MEMORIES</span><strong>Everything is grouped inside its name</strong></div><small>{groups.length} section{groups.length === 1 ? '' : 's'} · {notes.length} items</small></div>
    <div className='rich-days'>{groups.length ? groups.map((name) => { const group = notes.filter((note) => (note.groupName || note.title || 'Travel Memory') === name); const count = (type: NoteType) => group.filter((note) => note.type === type).length; const latest = group[0]; return <div className={`rich-day ${visibleGroup === name ? 'active' : ''}`} key={name}><button className='rich-day-main' onClick={() => setSelectedGroup(name)}><span className='rich-calendar'>📍</span><div><strong>{groupLabel(name)}</strong><small>{latest?.trip || 'Current trip'} · 📷 ×{count('photo')} &nbsp; 📍 ×{count('location')} &nbsp; ☑️ ×{count('checklist')} &nbsp; 💵 ×{count('expense')} &nbsp; 🔗 ×{count('activity')}</small></div></button><button className='rich-day-edit' onClick={() => renameGroup(name)}>✎</button><button className='rich-view' onClick={() => setSelectedGroup(name)}>View All</button></div>; }) : <div className='rich-empty'>Enter a place or memory name, add content, and tap Save. A section will appear here.</div>}</div>
    {visibleGroup && groupNotes.length > 0 && <div className='rich-details'><div className='rich-details-heading'><strong>{groupLabel(visibleGroup)}</strong><span>{groupNotes.length} saved items</span></div>{groupNotes.map((note) => { const checked = note.data?.items?.filter((item) => item.checked).length || 0; const openLocation = () => { const location = note.data?.location; if (location) window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${location.name}, ${location.lat}, ${location.lon}`)}`, '_blank', 'noopener,noreferrer'); }; return <article className='rich-note-item' key={note.id} onClick={() => note.type === 'location' ? openLocation() : setDetail(note)}>{note.type === 'photo' ? <div className='rich-thumb'>{note.data?.src ? <img src={note.data.src} alt={note.title} /> : '📷'}</div> : <div className='rich-type-icon'>{note.type === 'checklist' ? '☑️' : note.type === 'expense' ? moneySymbol(note.data?.currency) : note.type === 'location' ? '📍' : note.type === 'activity' ? '🔗' : '📝'}</div>}<div className='rich-item-body'><div className='rich-item-top'><strong>{note.title}</strong>{note.type === 'expense' ? <b>{moneySymbol(note.data?.currency)}{note.data?.amount}</b> : <small>{note.createdAt}</small>}<div className='rich-item-actions' onClick={(event) => event.stopPropagation()}><button className='outline-button' onClick={() => updateNote(note)}>Edit</button><button className='outline-button rich-delete' onClick={() => deleteNote(note.id)}>Delete</button></div></div>{noteDescription(note) && <p className='rich-note-description'>{noteDescription(note)}</p>}{note.type === 'checklist' ? <><small>Checked: {checked}/{note.data?.items?.length || 0}</small><div className='rich-check-items'>{note.data?.items?.slice(0, 3).map((item, index) => <label key={index} onClick={(event) => event.stopPropagation()}><input type='checkbox' checked={item.checked} onChange={() => toggleItem(note.id, index)} /><span>{item.text}</span></label>)}</div></> : note.type === 'expense' ? <span className='rich-category'>{note.data?.category || 'Travel'}</span> : note.type === 'location' ? <div className='rich-map-preview'><iframe title={note.title} src={`https://www.openstreetmap.org/export/embed.html?bbox=${(note.data?.location?.lon || 0) - .015}%2C${(note.data?.location?.lat || 0) - .01}%2C${(note.data?.location?.lon || 0) + .015}%2C${(note.data?.location?.lat || 0) + .01}&layer=mapnik&marker=${note.data?.location?.lat || 0}%2C${note.data?.location?.lon || 0}`} loading='lazy' /></div> : <><p>{note.text}</p><a>Read More</a></>}</div></article>; })}<button className='rich-close-details' onClick={() => setSelectedGroup('')}>Close Section</button></div>}
    {notes.length > 0 && <div className='rich-history-clear'><div><span>DANGER ZONE</span><strong>Clear Notes History</strong><small>Remove every saved place, note, photo, location, checklist, expense and activity from this device.</small></div><button className='outline-button rich-delete' onClick={clearNotesHistory}>Clear All Notes History</button></div>}
    {detail && <div className='rich-fullscreen' onClick={() => setDetail(null)}><div className='rich-full-card' onClick={(event) => event.stopPropagation()}><button className='rich-x' onClick={() => setDetail(null)}>×</button><span>{detail.type.toUpperCase()} NOTE</span><h3>{detail.title}</h3><small>{detail.createdAt} · {detail.trip}</small>{detail.type !== 'text' && noteDescription(detail) && <div className='rich-content-description'><span>DETAILS</span><p>{noteDescription(detail)}</p></div>}{detail.type === 'photo' && detail.data?.src && <img className='rich-full-photo' src={detail.data.src} alt={detail.title} />}{detail.type === 'location' && detail.data?.location && <div className='rich-large-map'><iframe title='Tagged location' src={`https://www.openstreetmap.org/export/embed.html?bbox=${detail.data.location.lon - .03}%2C${detail.data.location.lat - .02}%2C${detail.data.location.lon + .03}%2C${detail.data.location.lat + .02}&layer=mapnik&marker=${detail.data.location.lat}%2C${detail.data.location.lon}`} /></div>}{detail.type === 'checklist' && <div className='rich-full-checklist'>{detail.data?.items?.map((item, index) => <label key={index}><input type='checkbox' checked={item.checked} onChange={() => toggleItem(detail.id, index)} /><span>{item.text}</span></label>)}</div>}{detail.type === 'expense' && <div className='rich-big-expense'><span>TOTAL SPENT</span><strong>{moneySymbol(detail.data?.currency)}{detail.data?.amount}</strong>{detail.data?.expenseItems?.length ? <div className='rich-full-expense-list'>{detail.data.expenseItems.map((item, index) => <div key={`${item.description}-${index}`}><span>{item.description}<small>{item.category}</small></span><b>{moneySymbol(detail.data?.currency)}{item.amount}</b></div>)}</div> : <small>{detail.data?.category || 'Travel'}</small>}</div>}{detail.type === 'activity' && <div className='rich-activity-box'>Linked activity: <b>{detail.data?.activity || detail.text}</b></div>}{detail.type === 'text' && <textarea className='rich-edit-text' defaultValue={detail.text} onBlur={(event) => { const value = event.currentTarget.value.trim(); if (value) { const next = notes.map((item) => item.id === detail.id ? { ...item, text: value, title: value.slice(0, 48) } : item); persist(next); setDetail(next.find((item) => item.id === detail.id) || null); } }} />}<button className='outline-button' onClick={() => updateNote(detail)}>Update Content</button><button className='outline-button rich-delete' onClick={() => deleteNote(detail.id)}>Delete Content</button></div></div>}
    {action === 'checklist' && <div className='rich-action-modal-backdrop' onClick={closeAction}><div className='rich-action-modal' onClick={(event) => event.stopPropagation()}><h3>Start Checklist</h3><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder='Checklist title' /><textarea value={checklist} onChange={(event) => setChecklist(event.target.value)} placeholder={'One item per line\nPassport\nTickets\nCharger'} /><button className='primary-button' onClick={saveChecklist}>Create Checklist</button></div></div>}
    {action === 'expense' && <div className='rich-action-modal-backdrop' onClick={closeAction}><div className='rich-action-modal' onClick={(event) => event.stopPropagation()}><h3>Log Trip Expenses</h3><p>Add every expense from this trip/place below. Save once and the total will be calculated automatically.</p>{expenseItems.length > 0 && <div className='rich-expense-items'>{expenseItems.map((item, index) => <div className='rich-expense-row' key={`${item.description}-${index}`}><div><strong>{item.description}</strong><small>{item.category}</small></div><b>{moneySymbol(currency)}{item.amount}</b><button className='outline-button rich-delete' onClick={() => removeExpenseItem(index)}>×</button></div>)}</div>}<div className='rich-form-grid'><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder='What was the expense? e.g. Hotel' /><input type='number' min='0' value={amount} onChange={(event) => setAmount(event.target.value)} placeholder='Amount' /></div><select value={category} onChange={(event) => setCategory(event.target.value)}><option>Food</option><option>Stay</option><option>Travel</option><option>Tickets</option><option>Shopping</option><option>Other</option></select><div className='rich-form-grid'><select value={currency} onChange={(event) => setCurrency(event.target.value)}><option>INR</option><option>EUR</option><option>USD</option><option>GBP</option></select><button className='outline-button' onClick={addExpenseItem}>+ Add this expense</button></div>{expenseItems.length > 0 && <div className='rich-expense-total'><span>Total</span><strong>{moneySymbol(currency)}{expenseTotal.toFixed(2)}</strong></div>}<button className='primary-button' onClick={saveExpense}>Save All Expenses</button></div></div>}
    {action === 'location' && <div className='rich-action-modal-backdrop' onClick={closeAction}><div className='rich-action-modal' onClick={(event) => event.stopPropagation()}><h3>Tag Location</h3><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder='Location note title' /><div className='rich-location-search'><input value={locationQuery} onChange={(event) => setLocationQuery(event.target.value)} placeholder='Search a place in India' /><button className='primary-button' onClick={() => void findLocation()}>Find</button></div><div className='rich-location-results'>{locations.map((item) => <button key={`${item.lat}-${item.lon}`} onClick={() => setPickedLocation({ name: item.name, lat: item.lat, lon: item.lon })}>📍 <strong>{item.name}</strong><small>{item.display}</small></button>)}</div>{pickedLocation && <div className='rich-large-map'><iframe title='Selected location' src={`https://www.openstreetmap.org/export/embed.html?bbox=${pickedLocation.lon - .015}%2C${pickedLocation.lat - .01}%2C${pickedLocation.lon + .015}%2C${pickedLocation.lat + .01}&layer=mapnik&marker=${pickedLocation.lat}%2C${pickedLocation.lon}`} /></div>}<button className='primary-button' disabled={!pickedLocation} onClick={saveLocation}>Save Location</button></div></div>}
    {action === 'activity' && <div className='rich-action-modal-backdrop' onClick={closeAction}><div className='rich-action-modal rich-activity-modal' onClick={(event) => event.stopPropagation()}><div className='rich-modal-head'><div><span>ACTIVITY</span><h3>Link Activity</h3><p>Add the plan once; the saved card stays compact.</p></div><button className='rich-modal-x' onClick={closeAction}>×</button></div><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder='Activity name · e.g. Ganga Aarti' /><div className='rich-form-grid'><input type='date' value={activityDate} onChange={(event) => setActivityDate(event.target.value)} aria-label='Activity date' /><input type='time' value={activityTime} onChange={(event) => setActivityTime(event.target.value)} aria-label='Activity time' /></div><div className='rich-form-grid'><input type='number' min='1' value={activityDuration} onChange={(event) => setActivityDuration(event.target.value)} placeholder='Duration (minutes)' /><input value={activityLocation} onChange={(event) => setActivityLocation(event.target.value)} placeholder='Location' /></div><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder='What do you need to do? Add extra details…' /><button className='primary-button' onClick={saveActivity}>Save Activity</button></div></div>}
  </section>;
}
