import { useState } from 'react';
import { X, Plus, Check, MapPin, Sparkles, GripVertical, Trash2, CalendarDays, Clock3, ImagePlus, ReceiptText, Link2 } from 'lucide-react';
import './focused.css';
type Mode = 'location'|'photo'|'checklist'|'expense'|'activity'|'note'|'summary';
type P = { id:string; name:string; location:string };
type E = { id:string; day:number; person:string; item:string; amount:number; currency:string; category:string; date:string; time:string; receipt?:string };
const KEY='golden-perfect-focused-expenses-v2';
const RATE:Record<string,number>={INR:1,USD:83.5,EUR:90,GBP:105};
const nowParts=()=>{const d=new Date();return {date:d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}),time:d.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}};
export default function FocusedTravelTool({mode,place,onClose,onSaveNote,onSaveLocation,notify}:{mode:Mode;place?:P;onClose:()=>void;onSaveNote:(d:any)=>boolean;onSaveLocation:(id:string,l:string)=>void;notify?:(m:string)=>void}){
 const now=nowParts();
 const [day,setDay]=useState(1); const [date,setDate]=useState(now.date); const [time,setTime]=useState(now.time); const [loc,setLoc]=useState(place?.location||''); const [caption,setCaption]=useState(''); const [tags,setTags]=useState('#photo, #scenery');
 const [text,setText]=useState(''); const [activity,setActivity]=useState('');
 const [ci,setCi]=useState(''); const [checks,setChecks]=useState<Array<{text:string;done:boolean}>>([]);
 const [photos,setPhotos]=useState<string[]>([]);
 const [person,setPerson]=useState('Self'); const [customPayer,setCustomPayer]=useState(''); const [item,setItem]=useState(''); const [amt,setAmt]=useState(''); const [cur,setCur]=useState('INR'); const [category,setCategory]=useState('Sightseeing'); const [receipt,setReceipt]=useState(''); const [lastAddedExpense,setLastAddedExpense]=useState<E|null>(null);
 const [ex,setEx]=useState<E[]>(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')[place?.id||'']||[]}catch{return[]}});
 const saveEx=(n:E[])=>{try{const all=JSON.parse(localStorage.getItem(KEY)||'{}');all[place?.id||'']=n;localStorage.setItem(KEY,JSON.stringify(all));setEx(n);return true}catch(error){if(error instanceof DOMException&&error.name==='QuotaExceededError')notify?.('Storage full — delete old photos or notes.');else notify?.('Could not save this expense on this device.');return false}};
 const addEx=()=>{const n=Number(amt);const payer=person==='Other'?customPayer.trim():person.trim();if(!payer||!item.trim()||!n){notify?.('Enter payer, description and amount.');return}const entry:E={id:crypto.randomUUID(),day,person:payer,item:item.trim(),amount:n,currency:cur,category,date,time,receipt};saveEx([...ex,entry]);setLastAddedExpense(entry);setItem('');setAmt('');setReceipt('');setCustomPayer('');if(person==='Other')setPerson('Self');};
 const compressImage=(file:File,maxDimension=1000,quality=0.68):Promise<string>=>new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(r.error||new Error('read failed'));r.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('decode failed'));img.onload=()=>{const scale=Math.min(1,maxDimension/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round((img.naturalWidth||img.width)*scale));canvas.height=Math.max(1,Math.round((img.naturalHeight||img.height)*scale));const ctx=canvas.getContext('2d');if(!ctx){reject(new Error('canvas unavailable'));return}ctx.drawImage(img,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(!blob){reject(new Error('compression failed'));return}const out=new FileReader();out.onload=()=>resolve(String(out.result||''));out.onerror=()=>reject(out.error||new Error('encode failed'));out.readAsDataURL(blob)},'image/jpeg',quality)};img.src=String(r.result||'')};r.readAsDataURL(file)});
 const addFiles=(fs:FileList|null)=>{if(!fs)return;Array.from(fs).forEach(f=>{void compressImage(f).then(photo=>setPhotos(p=>[...p,photo])).catch(()=>notify?.('Could not process this photo. Try another image.'))})};
 const addReceipt=(f:File|undefined)=>{if(!f)return;void compressImage(f,900,0.65).then(setReceipt).catch(()=>notify?.('Could not process this receipt. Try another image.'))};
 const total=ex.reduce((s,e)=>s+e.amount*(RATE[e.currency]||1),0); const dayTotal=ex.filter(e=>e.day===day).reduce((s,e)=>s+e.amount*(RATE[e.currency]||1),0);
 const title=mode==='location'?'Location Details':mode==='photo'?'New Media Note':mode==='checklist'?'Gateway Checklist Details':mode==='expense'?'Edit Gateway Expense Details':mode==='activity'?'Activity Details':mode==='summary'?'Trip Summary: '+(place?.name||''):'Add New Note in '+(place?.name||'Trip');
 const save=()=>{if(!place)return;if(mode==='location'){if(!loc.trim())return notify?.('Add a location first.');onSaveLocation(place.id,loc.trim());notify?.('Location saved.');return onClose()}if(mode==='expense'){const entry=lastAddedExpense;if(!entry)return notify?.('Add an expense first.');const ok=onSaveNote({mode:'expense',day:entry.day,date:entry.date,time:entry.time,title:entry.item,text:`${entry.person} · ${entry.item}`,expenseLabel:entry.category,expenseAmount:entry.amount});if(!ok)return;notify?.('Expense saved to My Travel Notes.');return onClose()}if(mode==='photo'){if(!photos.length)return notify?.('Add at least one photo.');const ok=onSaveNote({mode,day,date,time,title:'Photo Memory',text:caption||'Photo memory',photo:photos[0]});if(!ok)return;notify?.('Photo saved to My Travel Notes.');return onClose()}if(mode==='checklist'){if(!checks.length)return notify?.('Add a checklist item.');const ok=onSaveNote({mode,day,date,time,title:'Gateway Checklist',text:checks.filter(x=>x.done).length+'/'+checks.length+' completed',checklist:checks.map(x=>x.text)});if(!ok)return;notify?.('Checklist saved to My Travel Notes.');return onClose()}if(mode==='activity'){if(!activity.trim())return notify?.('Add an activity.');const ok=onSaveNote({mode,day,date,time,title:activity,text:activity});if(!ok)return;notify?.('Activity saved to My Travel Notes.');return onClose()}if(!text.trim()&&mode==='note')return notify?.('Write a note first.');const ok=onSaveNote({mode:'note',day,date,time,title:text.trim().slice(0,60)||'New Note',text,checklist:[]});if(!ok)return;notify?.('Note saved to My Travel Notes.');onClose()};
 const addCheck=()=>{if(ci.trim()){setChecks([...checks,{text:ci.trim(),done:false}]);setCi('')}};
 const removeCheck=(i:number)=>setChecks(checks.filter((_,j)=>j!==i));
 const toggleCheck=(i:number)=>setChecks(checks.map((x,j)=>j===i?{...x,done:!x.done}:x));
 const moveCheck=(i:number,dir:number)=>{const j=i+dir;if(j<0||j>=checks.length)return;const n=[...checks];[n[i],n[j]]=[n[j],n[i]];setChecks(n)};
 return <div className='travel-notes-modal-backdrop' onClick={onClose}><section className='travel-focused-modal reference-exact-modal' onClick={e=>e.stopPropagation()}>
 <header className='travel-focused-header'><div><strong>{title}</strong><small>{place?.name} · Travel Notes</small></div><button onClick={onClose}><X size={20}/></button></header>
 {mode==='summary'?<div className='travel-summary-content'><div className='travel-summary-total'><span>Total Trip Spend in {place?.name}</span><strong>₹{total.toLocaleString('en-IN')}</strong></div><div className='travel-summary-card'><strong>Day-wise Summary</strong>{[...new Set(ex.map(e=>e.day))].sort((a,b)=>a-b).map(d=><button key={d} onClick={()=>setDay(d)}>Day {d}<b>₹{ex.filter(e=>e.day===d).reduce((s,e)=>s+e.amount*(RATE[e.currency]||1),0).toLocaleString('en-IN')}</b></button>)}</div><div className='travel-summary-card'><strong>Person-wise Summary</strong>{[...new Set(ex.map(e=>e.person))].map(p=><div key={p}>{p}<b>₹{ex.filter(e=>e.person===p).reduce((s,e)=>s+e.amount*(RATE[e.currency]||1),0).toLocaleString('en-IN')}</b></div>)}</div><div className='travel-summary-card'><strong>Detailed Expenses</strong>{ex.map(e=><div key={e.id}>Day {e.day} · {e.person} · {e.item}<b>{e.currency} {e.amount}</b></div>)}</div></div>:
 <div className='travel-focused-body'>
 {mode!=='note'&&mode!=='activity'&&<div className='reference-top-fields'><label>Date<input type='text' value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<select value={time} onChange={e=>setTime(e.target.value)}><option value={now.time}>current</option><option>09:00 AM</option><option>12:00 PM</option><option>02:00 PM</option><option>06:00 PM</option><option>08:00 PM</option></select></label></div>}
 {mode==='photo'&&<><div className='reference-media-drop'><ImagePlus size={42}/><strong>Add Media</strong><span>Tap to choose one or more travel photos</span><input hidden id='reference-photo-input' type='file' accept='image/*' multiple onChange={e=>addFiles(e.target.files)}/><button onClick={()=>document.getElementById('reference-photo-input')?.click()}>＋ Add Media</button></div><div className='reference-photo-strip'>{photos.map((p,i)=><img key={i} src={p} alt='Travel memory'/>)}</div><label>Caption<input value={caption} onChange={e=>setCaption(e.target.value)} placeholder='Type photo details...'/></label><label>Location<div className='travel-focused-location-input'><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder='Add location'/><MapPin size={17}/></div></label><label>Tags<input value={tags} onChange={e=>setTags(e.target.value)} placeholder='#photo #scenery #food'/></label></>}
 {mode==='checklist'&&<><div className='reference-check-summary'><span>Gateway Checklist</span><b>{checks.filter(x=>x.done).length}/{checks.length||0}</b></div><div className='travel-focused-add-row'><input value={ci} onChange={e=>setCi(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addCheck()}} placeholder='Add new item'/><button onClick={addCheck}><Plus size={18}/></button></div>{checks.map((x,i)=><div className={'reference-check-item '+(x.done?'done':'')} key={i}><button onClick={()=>toggleCheck(i)}>{x.done?'✓':'○'}</button><span>{x.text}</span><button onClick={()=>moveCheck(i,-1)}><GripVertical size={16}/></button><button onClick={()=>removeCheck(i)}><Trash2 size={15}/></button></div>)}</>}
 {mode==='expense'&&<><div className='reference-expense-amount'><span>₹</span><input value={amt} onChange={e=>setAmt(e.target.value)} placeholder='600.00' type='number'/></div><div className='reference-two-col'><label>Date<input value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input value={time} onChange={e=>setTime(e.target.value)}/></label></div><div className='reference-two-col'><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Sightseeing</option><option>Food</option><option>Hotel</option><option>Transport</option><option>Shopping</option><option>Other</option></select></label><label>Payer<select value={person} onChange={e=>{setPerson(e.target.value);if(e.target.value!=='Other')setCustomPayer('')}}><option>Self</option><option>Abhay</option><option>Other</option></select></label></div>{person==='Other'&&<label>Other Payer Name<input value={customPayer} onChange={e=>setCustomPayer(e.target.value)} placeholder='Enter payer name'/></label>}<label>Description<input value={item} onChange={e=>setItem(e.target.value)} placeholder='Souvenirs and snacks'/></label><div className='reference-receipt-box'><ReceiptText size={28}/><strong>Add Receipt Photo</strong><span>Clear dashed boundary for receipt</span>{receipt&&<img src={receipt} alt='Receipt'/>}<input hidden id='reference-receipt-input' type='file' accept='image/*' onChange={e=>addReceipt(e.target.files?.[0])}/><button onClick={()=>document.getElementById('reference-receipt-input')?.click()}>＋ Add Receipt</button></div><button className='travel-add-expense' onClick={addEx}>+ Add / Save Expense Item</button><div className='travel-day-total'>Day {day} Total <b>₹{dayTotal.toLocaleString('en-IN')}</b></div>{ex.filter(e=>e.day===day).map(e=><div className='travel-expense-row' key={e.id}>{e.person} · {e.item}<b>{e.currency} {e.amount}</b></div>)}</>}
 {mode==='note'&&<><label>City / Trip<select value={place?.id||''} disabled><option>{place?.name||'Trip'}</option></select></label><label>Title<input value={text.split('\n')[0]||''} onChange={e=>setText(e.target.value+'\n'+(text.split('\n').slice(1).join('\n')))} placeholder='New Note Title...'/></label><label>Details<textarea value={text.split('\n').slice(1).join('\n')} onChange={e=>setText((text.split('\n')[0]||'New Note')+'\n'+e.target.value)} placeholder='Note Details...'/></label><div className='reference-two-col'><label>Date<input value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input value={time} onChange={e=>setTime(e.target.value)}/></label></div><div className='reference-attach-grid'><button onClick={()=>{setText(text);notify?.('Checklist attachment selected — add items from Quick Add Checklist.')}}><Check/> Checklist</button><button onClick={()=>notify?.('Expense attachment selected — use Quick Add Expense to add details.')}><span>₹</span> Expense</button><button onClick={()=>notify?.('Media attachment selected — use Quick Add Photo to attach media.')}><ImagePlus/> Media</button></div></>}
 {mode==='location'&&<><label>Location Name<input value={loc} onChange={e=>setLoc(e.target.value)}/></label><label>Address<div className='travel-focused-location-input'><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder='Address in address...'/><MapPin size={17}/></div></label><button className='reference-map-button' onClick={()=>window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(loc),'_blank')}>Open in Maps</button></>}
 {mode==='activity'&&<label>Activity<textarea value={activity} onChange={e=>setActivity(e.target.value)} placeholder='What happened?'/></label>}
 <div className='travel-focused-actions'><button className='outline-button' onClick={onClose}>Cancel</button><button className='primary-button small-button' onClick={save}>{mode==='photo'?'Save Media Note':mode==='checklist'?'Save Checklist':mode==='expense'?'Update Expense':mode==='note'?'Add Note':'Save'}</button></div>
 </div>}
 </section></div>;
}